Tune update-monitor deployment schedule (#10946)
Signed-off-by: Konrad <arukopay@gmail.com>

diff --git a/.github/workflows/deploy-update-monitor.yml b/.github/workflows/deploy-update-monitor.yml
--- a/.github/workflows/deploy-update-monitor.yml
+++ b/.github/workflows/deploy-update-monitor.yml
@@ -7,15 +7,21 @@ permissions:
   packages: write
 
 on:
-  workflow_dispatch: {}
+  workflow_dispatch:
+    inputs:
+      force:
+        description: "Skip check and always pass"
+        required: false
+        type: boolean
+        default: false
   schedule:
-    - cron: "45 * * * *"
+    - cron: "30 * * * *"
 
 jobs:
   deploy-update-monitor:
     name: Deploy update monitor
     runs-on: ubuntu-latest
-    timeout-minutes: 10
+    timeout-minutes: 30
     env:
       COOLIFY_SERVER: ${{ secrets.COOLIFY_SERVER }}
       COOLIFY_API_KEY: ${{ secrets.COOLIFY_DEPLOY_API_KEY }}
@@ -48,6 +54,31 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Wait until we're in last quarter of hour
+        run: |
+          check_minutes() {
+            local minutes=$(date +%M)
+            if [ $minutes -ge $1 ] && [ $minutes -le $2 ]; then
+              return 0
+            else
+              return 1
+            fi
+          }
+
+          if ${{ inputs.force }}; then
+            echo "Forced run, skipping checks"
+            exit 0
+          fi
+
+          if check_minutes 55 60 || check_minutes 0 30; then
+            echo "It's too late, failing!"
+            exit 1
+          fi
+          until check_minutes 45 55; do
+            echo "It's too early, sleeping for 30s"
+            sleep 30
+          done
+
       - name: Build and publish containers
         uses: docker/build-push-action@v6
         with:
@@ -62,6 +93,27 @@ jobs:
             TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+      - name: Don't release just before full hour
+        run: |
+          check_minutes() {
+            local minutes=$(date +%M)
+            if [ $minutes -ge $1 ]; then
+              return 0
+            else
+              return 1
+            fi
+          }
+
+          if ${{ inputs.force }}; then
+            echo "Forced run, skipping checks"
+            exit 0
+          fi
+
+          if check_minutes 57; then
+            echo "It's too late, failing!"
+            exit 1
+          fi
+
       - name: Release published containers (coolify)
         run: |
           set -ex
